export const USER_LOGIN_FETCH = "USER_LOGIN_FETCH";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";


export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FETCH = "USER_REGISTER_FETCH";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";


export const SUB_TOTAL_FETCH = "SUB_TOTAL_FETCH";
export const SUB_TOTAL_SUCCESS = "SUB_TOTAL_SUCCESS";
export const SUB_TOTAL_FAILURE = "SUB_TOTAL_FAILURE";

export const ADD_ITEM_FETCH = "ADD_ITEM_FETCH";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

export const DELETE_ITEM_FETCH = "DELETE_ITEM_FETCH";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";

